- name: Waiting for SSH connection
  wait_for_connection:
    delay: 30
    timeout: 300

- name: Gathering facts
  setup:

- name: Cloning MoonStack install directory
  git:
    repo: "https://gitee.com/stackw0rm/MoonStack-v2.git"
    dest: /root/moon

- name: Prepare to set user password 
  set_fact:
    user_name: "{{ ansible_user }}"
    user_password: "{{ user_password }}"
    user_salt: "s0mew1ck3dM00NStack"

- name: Changing password for user {{ user_name }} to {{ user_password }}
  user:
   name: "{{ ansible_user }}"
   password: "{{ user_password | password_hash('sha512', user_salt) }}"
   state: present
   shell: /bin/bash
   update_password: always

- name: Copy MoonStack configuration file
  template:
    src: ../../../../../../iso/installer/moon.conf.dist
    dest: /root/moon.conf
    owner: root
    group: root
    mode: 0644

- name: Install MoonStack on instance -  be patient, this might take 15 to 30 minutes depending on the connection speed. No further output is given.
  command: /root/moon/iso/installer/install.sh --type=auto --conf=/root/moon.conf

- name: Delete MoonStack configuration file
  file:
    path: /root/moon.conf
    state: absent

- name: Change unattended-upgrades to take default action
  blockinfile:
    dest: /etc/apt/apt.conf.d/50unattended-upgrades
    block: |
      Dpkg::Options {
        "--force-confdef";
        "--force-confold";
      }
