#cloud-config
timezone: UTC

package_update: true
package_upgrade: true
package_reboot_if_required: true

packages:
  - git

runcmd:
  - git clone https://gitee.com/stackw0rm/MoonStack-v2.git /root/moon
  - /root/moon/iso/installer/install.sh --type=auto --conf=/root/moon.conf
  - rm /root/moon.conf
  - /sbin/shutdown -r +5

# The contents of moon.conf will be base64 encoded and appended to this file
# via the terraform configuration in main.tf
#
# Make sure there are no trailing new lines after "permissions" below
write_files:
  - encoding: b64
    owner: root:root
    path: /root/moon.conf
    permissions: '0600'
