- name: Finally rebooting MoonStack in one minute
  shell: /sbin/shutdown -r -t 1
  become: true

- name: Next login options
  debug:
    msg:
    - "*****    SSH Access:"
    - "*****    ssh {{ ansible_user }}@{{ ansible_host }} -p 64295"
    - ""
    - "*****    Web UI:"
    - "*****    https://{{ ansible_host }}:64297"
    - ""
    - "*****    Admin UI:"
    - "*****    https://{{ ansible_host }}:64294"
